### ISSUE TITLE
Add a banner to root.cern/d ..

### ISSUE THREAD

**Issue by couet** [root-project/web#511]
... that tells users that they are looking at old, possibly deprecated pages.
Not sure if it is easy to do.

**Comment by ynikitenko** [comment]
There is a file https://root.cern/d/sites/d35c7d8c.web.cern.ch/files/website-banner-allnew-croped_3.png, which is the top banner on that site (the image on the current site root.cern has a different path).
I prepared two images about deprecation. Compare which one might look better.
It may take time to reload your CMS (if that is off), but to change one static file should be simple.
Hope this helps.
Anyway if you think that another text would be better, it's trivial to create it yourself with gimp.
![website-banner-allnew-croped_3_deprecation](https://user-images.githubusercontent.com/1204978/109658446-a71dba00-7b77-11eb-8213-2a32474cf649.png)
![website-banner-allnew-croped_3_deprecation_transparent](https://user-images.githubusercontent.com/1204978/109658460-a9801400-7b77-11eb-8aee-ce6a01313b5c.png)

**Comment by couet** [comment]
We have one already. It will be soon on.
![website-banner-allnew-croped_3](https://user-images.githubusercontent.com/4697738/109659762-5357a480-7b68-11eb-9ef3-364f81539b7d.png)

**Comment by ynikitenko** [comment]
Excellent. I was confused by your "Not sure if it is easy to do." in several places.

**Comment by couet** [comment]
Yes we ended up with the same solution but we did not update/close this issue as it is not yet online. 
I will close it once it will be active.

**Comment by couet** [comment]
done:  https://root.cern/d/index.html

**Comment by ynikitenko** [comment]
Many thanks for your work! I'm very glad that now less people will be confused if they found an outdated page.

Out of curiosity, I found several pages available from that site where the deprecation banner is missing.
These are documentation links from
https://root.cern/d/root-user-guides-and-manuals.html,
for example, http://root.cern.ch/root/htmldoc/guides/users-guide/ROOTUsersGuide.html

The main page of https://root.cern.ch/ looks like the new site root.cern . 
But the page http://root.cern.ch/root/htmldoc/ looks like some third site.
I don't know what root.cern.ch means now, but maybe you could change the banner of http://root.cern.ch/root/htmldoc/ ?

I can see that e.g. http://root.cern.ch/root/htmldoc/THtml.html is outdated, because a more recent version at https://root.cern/doc/master/classTHtml.html (which redirects from the previous link if you remove 'ch') clearly indicates that that class is deprecated.

**Comment by eguiraud** [comment]
root.cern.ch and root.cern are equivalent. https://root.cern/root/htmldoc should likely not be there not be visible (right @couet ?), and https://root.cern/root should also likely not be a thing..?

**Comment by ynikitenko** [comment]
@couet would you mind reopening this issue, or shall we create a new one?

**Comment by couet** [comment]
I think the banner was added to root.CERN/d

Envoyé de mon iPhone

**Comment by Axel-Naumann** [comment]
> I can see that e.g. http://root.cern.ch/root/htmldoc/THtml.html is outdated, because a more recent version at https://root.cern/doc/master/classTHtml.html (which redirects from the previous link if you remove 'ch') clearly indicates that that class is deprecated.

http://root.cern.ch/root/htmldoc/THtml.html now also redirects to https://root.cern/doc/master/classTHtml.html - thanks for pointing that out!
