### ISSUE TITLE
Highlight main menu item of current site

### ISSUE THREAD

**Issue by bernhardmgruber** [root-project/web#69]
I would like to have the item in the top main menu highlighted that corresponds to the page I have currently opened.

E.g. when I click on "Download" and then navigate through the subitems on the right, I would like the "Download" to always be somehow emphazised.

**Comment by couet** [comment]
I am not exactly what you are talking about but it looks like you would like to have some highlights in the right menu. For instance on this page: https://root.cern/manual/first_steps_with_root/
Well, such a feature is not supported in the menu on the right. Also, I am not sure what should be highlighted in a such case. Can we close this issue ? it does not seem that's something people require anyway.

**Comment by bernhardmgruber** [comment]
On the page you just linked:
![image](https://user-images.githubusercontent.com/1224051/193015798-074018ac-f957-4ae3-b312-a52150933fe2.png)
The entry "First steps with ROOT" is highlighted, which is great!
However, the entry "Manual" is not highlighted. It would help me if you could also highlight the currently open site on this main menu at the top.

> Can we close this issue ? it does not seem that's something people require anyway.

That is up to you. I opened this issue as part of the website review we had years ago, because it bothered me. If you don't care, then close it as won't fix :)

**Comment by couet** [comment]
I see what you mean, that's not really doable because you can end up to these pages without coming via the manual menu. Generally speaking there is no direct dependency between the top bar and the rest of the website (pages can be accessed multiple ways). Finally from a technical point of view, the Jekyll machinery does not provide such a highlight mechanism. I will close. Thanks for your feedback.

**Comment by bernhardmgruber** [comment]
Ok, that makes sense then! Thx!
